cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'imagemagick'
brew 'openssl'
brew 'node'
brew 'wget'
brew 'git'
brew 'readline'
brew 'python'
brew 'ruby'
brew 'vim'

cask 'atom'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'webpquicklook'
cask 'vagrant'
cask 'virtualbox'
cask 'spectacle'
cask 'caffeine'
