alias gulp='$(npm bin)/gulp'
alias grunt='$(npm bin)/grunt'
alias electron='$(npm bin)/electron'
alias asar='$(npm bin)/asar'
alias ng='$(npm bin)/ng'
alias ngc='$(npm bin)/ngc'
alias tsc='$(npm bin)/tsc'
alias typings='$(npm bin)/typings'
